services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: geoint_postgres
    environment:
      POSTGRES_USER: geoint
      POSTGRES_PASSWORD: geoint_pass
      POSTGRES_DB: geoint_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: geoint_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: